UltaTest/Models/BaseModel.cs
namespace UltaTest.Models
{
    public abstract class BaseModel
    {
        public int Id { get; set; }
    }
}

UltaTest/Models/PagedList.cs
using System;
using System.Collections.Generic;

namespace UltaTest.Models
{
    public class PagedList<T>
    {
        public List<T> Content { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int TotalRecords
        {
            get { return Content.Count; }
        }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalRecords / PageSize); }
        }
    }
}

UltaTest/Models/PatientModel.cs
using FluentValidation.Attributes;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using UltaTest.Validations;

namespace UltaTest.Models
{
    [Validator(typeof(PatientValidation))]
    public class PatientModel : BaseModel
    {
        public string Name { get; set; }

        public string Address { get; set; }

        public string Email { get; set; }

        [DisplayName("Date Of Birth")]
        public DateTime DateOfBirth { get; set; }

        public Gender Gender { get; set; }

        public int Age
        {
            get
            {
                var age = DateTime.Now.Year - DateOfBirth.Year;
                if (DateTime.Now.DayOfYear < DateOfBirth.DayOfYear)
                    age = age - 1;

                return age;
            }
        }
    }

    public enum Gender
    {
        NotSpecified,
        Male,
        Female,
    }
}

UltaTest/Controllers/PatientController.cs
using AutoMapper;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UltaTest.Data.Domains;
using UltaTest.Helpers;
using UltaTest.Models;
using UltaTest.Services;

namespace UltaTest.Controllers
{
    public class PatientController : Controller
    {
        public readonly IPatientService _patientService;
        private readonly IMapper _mapper;

        public PatientController(IPatientService patientService, IMapper mapper)
        {
            _patientService = patientService;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string filter = "")
        {
            try
            {
                var patients = _patientService.ListAll(filter).ToList();

                var model = new PagedList<PatientModel>
                {
                    PageSize = 999,
                    Content = _mapper.Map<List<PatientModel>>(patients)
                };

                return PartialView("_List", model);
            }
            catch (Exception ex)
            {
                NotificationsHelper.AddNotification(new Notification { Message = ex.Message, NotificationType = NotificationType.Error, Title = "Error" });
            }

            return PartialView("_List", new PagedList<PatientModel> { PageSize = 1, Content = new List<PatientModel>() });
        }

        public PartialViewResult AddOrEdit(int id = 0)
        {
            var model = new PatientModel() { DateOfBirth = new DateTime(1980, 1, 1) };

            if (id > 0)
            {
                try
                {
                    var patient = _patientService.GetById(id);
                    model = _mapper.Map<PatientModel>(patient);
                }
                catch (Exception ex)
                {
                    NotificationsHelper.AddNotification(new Notification { Message = ex.Message, NotificationType = NotificationType.Error, Title = "Error" });
                }
            }

            return PartialView("_AddOrEdit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(PatientModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var patient = _mapper.Map<Patient>(model);

                    if (patient.Id > 0)
                    {
                        _patientService.Update(patient);
                        NotificationsHelper.AddNotification(new Notification { Message = "Patient profile was updated!", NotificationType = NotificationType.Success });
                    }
                    else
                    {
                        _patientService.Add(patient);
                        NotificationsHelper.AddNotification(new Notification { Message = "New patient was added!", NotificationType = NotificationType.Success });
                    }
                }
                catch (Exception ex)
                {
                    NotificationsHelper.AddNotification(new Notification { Message = ex.Message, NotificationType = NotificationType.Error, Title = "Error" });
                }
            }
            else
                NotificationsHelper.AddNotification(new Notification { Message = String.Join("<br>", ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToArray()), NotificationType = NotificationType.Error, Title = "Error" });

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                _patientService.Delete(id);
                NotificationsHelper.AddNotification(new Notification { Message = "Patient was deleted!", NotificationType = NotificationType.Success });
            }
            catch (Exception ex)
            {
                NotificationsHelper.AddNotification(new Notification { Message = ex.Message, NotificationType = NotificationType.Error, Title = "Error" });
            }

            return RedirectToAction("Index");
        }
    }
}

UltaTest/Views/Patient/Index.cshtml
<div class="container">
    <div class="row flex-lg-nowrap">
        <div class="col">
            <div class="row">
                <div class="col-12 mb-3">
                    <div class="card">
                        <div class="row card-body">
                            <div class="col col-9">
                                <div>
                                    Search: 
                                    <div class="input-group-append">
                                        <input class="form-control w-100 mr-1" type="text" placeholder="Name" value="" id="searchFilter">
                                        <button class="btn btn-secondary" type="button" id="searchButton">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="col text-center col-3">
                                &nbsp;
                                @Ajax.ActionLink("New Patient",
                                                 "AddOrEdit",
                                                 new { id = 0 },
                                                 new AjaxOptions
                                                 {
                                                    UpdateTargetId = "details",
                                                    InsertionMode = InsertionMode.Replace,
                                                    OnSuccess = "Done()"
                                                 },
                                                 new { @class = "btn btn-success btn-block" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 mb-3" id="patientList">
                    @Html.Action("List")
                </div>
            </div>
            <div id="details"></div>
        </div>
    </div>
</div>
<form method="post" id="modal-form" action="">
    @Html.AntiForgeryToken()
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <p>You are about to delete <b><i class="title"></i></b>'s record, this procedure is irreversible.</p>
                    <p>Do you want to proceed?</p>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-md btn-outline-secondary" data-dismiss="modal">
                        <i class="fa fa-reply"></i> Cancel
                    </button>
                    <button type="submit" class="btn btn-md btn-danger">
                        <i class="fa fa-times"></i> Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

UltaTest/Views/Patient/_AddOrEdit.cshtml
@using UltaTest.Models;
@model PatientModel

<div class="modal fade" role="dialog" tabindex="-1" id="user-form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@(Model.Id > 0 ? "Update" : "Add")  Patient</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="py-1">
                    @using (Html.BeginForm("AddOrEdit", "Patient", FormMethod.Post, new { id = "patientForm" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(p => p.Id)
                        <div class="row mb-5">
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            @Html.LabelFor(p => p.Name)
                                            @Html.EditorFor(p => p.Name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(p => p.Name, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            @Html.LabelFor(p => p.Address)
                                            @Html.EditorFor(p => p.Address, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(p => p.Address, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            @Html.LabelFor(p => p.Email)
                                            @Html.EditorFor(p => p.Email, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(p => p.Email, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            @Html.LabelFor(p => p.DateOfBirth)
                                            @Html.TextBoxFor(model => model.DateOfBirth, new { @type = "date", @class = "form-control datepicker", @Value = Model.DateOfBirth.ToString("yyyy-MM-dd") })
                                            @Html.ValidationMessageFor(p => p.DateOfBirth, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            @Html.LabelFor(p => p.Gender)
                                            @Html.DropDownListFor(o => o.Gender, Enum.GetValues(typeof(Gender)).Cast<Gender>().Select(x => new SelectListItem { Text = x.ToString(), Value = ((int)x).ToString() }), new { @class = "form-control" })
                                            @Html.ValidationMessageFor(p => p.Gender, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col d-flex justify-content-end">
                                <button class="btn btn-primary" type="submit">Save Changes</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

UltaTest/Views/Patient/_List.cshtml
@using UltaTest.Models;
@model PagedList<PatientModel>

<div class="e-panel card">
    <div class="card-body">
        <div class="card-title">
            <h6 class="mr-2"><span>Patients</span></h6>
        </div>
        <div class="e-table">
            <div class="table-responsive table-lg mt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="max-width sortable">Name</th>
                            <th>Address</th>
                            <th class="sortable">E-mail</th>
                            <th>Date of Birth</th>
                            <th>Gender</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Content != null && Model.Content.Any())
                        {
                            foreach (var patient in Model.Content)
                            {
                                <tr>
                                    <td class="text-nowrap align-middle">@patient.Name</td>
                                    <td class="text-nowrap align-middle">@patient.Address</td>
                                    <td class="text-left align-middle">@patient.Email</td>
                                    <td class="text-left align-middle">@patient.DateOfBirth.ToString("MM/dd/yyyy") (Age: @patient.Age)</td>
                                    <td class="text-left align-middle">@patient.Gender.ToString()</td>
                                    <td class="text-center align-middle">
                                        <div class="btn-group align-top">
                                            @Ajax.ActionLink("Edit",
                                                             "AddOrEdit",
                                                             new { id = patient.Id },
                                                             new AjaxOptions
                                                             {
                                                                 UpdateTargetId = "details",
                                                                 InsertionMode = InsertionMode.Replace,
                                                                 OnSuccess = "Done()"
                                                             },
                                                             new { @class = "btn btn-sm btn-outline-secondary badge" })
                                            <button type="button" data-href="/patient/delete/@patient.Id" data-toggle="modal" data-target="#confirm-delete" data-record-title="@patient.Name" name="delete-@patient.Id" class="btn btn-sm btn-outline-secondary badge"><i class="fa fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="6" class="text-nowrap align-middle text-center">No data found.</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

UltaTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ulta Test</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Ulta Test", "Patient", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
    </nav>

    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval")

    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ulta Test - By Ivan Schiavinatto</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @Html.Raw(UltaTest.Helpers.NotificationsHelper.RenderNotifications())
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        function Done() {
            $('#user-form-modal').modal('show');
        }

        $('#confirm-delete').on('show.bs.modal', function (e) {
            var data = $(e.relatedTarget).data();

            $('#modal-form').attr('action', data.href);
            $('#modal-form .title').text(data.recordTitle);
        });

        $('#searchButton').click(function (event) {
            $(function () {
                $.ajax({
                    url: '/patient/list',
                    type: 'get',
                    data: { filter: $('#searchFilter').val() },
                    success: function (result) {
                        $('#patientList').html(result);
                    }
                });
            });
        });
    </script>
</body>
</html>